# Generated by Django 2.1.5 on 2019-01-09 03:50

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default=datetime.datetime(2019, 1, 9, 3, 50, 23, 183931, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
