# Generated by Django 2.1.5 on 2019-01-09 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190109_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='brithdate',
            new_name='birthdate',
        ),
    ]
